version: 0.1
runson: win
maxRetries: 2
concurrency: 3
autosplit: true
pre:
  - npm install

cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: node -e "const c = require('./nightwatch.conf.js'); console.log(Object.keys(c.test_settings).filter(k => ['chrome','firefox','edge'].includes(k)).join('\n'))"
testRunnerCommand: ./node_modules/.bin/nightwatch -e $test

jobLabel: [selenium-Nightwatch, win, autosplit-simple]